### ISSUE TITLE
Gebruik exception handling

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/PHP_WEBSHOP#1]
https://github.com/vincentlemstra/PHP_WEBSHOP/blob/faff7201c6a1faae091516ab9fd17c9053a9c798/src/controllers/ajax.controller.php#L43

In handlerequest heb je een try...catch die ervoor zorgt dat bij fout een andere header+foutmelding wordt gestuurd.
Zorg dan dat dit mechanisme ook wordt gebruikt dmv "throw new Exception(...)" ipv "echo ...."

**Comment by vincentlemstra** [comment]
Catch blok: 

catch (Exception $e) {
            // stop and empty buffer     
            ob_end_clean();
            // send error header + error message 
            header('HTTP/1.1 500 Internal Server Error');
            throw new Exception($e->getMessage());
        }

In een volgende standup wil ik hier wel graag een vraag over stellen. Ik heb niet helemaal helder wat dit **exact** doet
