### ISSUE TITLE
Waarom niet in BaseController?

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/PHP_WEBSHOP#2]
https://github.com/vincentlemstra/PHP_WEBSHOP/blob/faff7201c6a1faae091516ab9fd17c9053a9c798/src/controllers/page.base.controller.php#L16

Ook je andere Controllers kunne deze functie goed gebruiken!

**Comment by vincentlemstra** [comment]
protected function getRequestVar -> moved to BaseController
