### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/PHP_WEBSHOP#3]
https://github.com/vincentlemstra/PHP_WEBSHOP/blob/faff7201c6a1faae091516ab9fd17c9053a9c798/src/controllers/page.controller.php#L105

aanroep van show() kan NA de switch....

**Comment by vincentlemstra** [comment]
Nieuw variable $handler. Deze wordt **IN** de switch gevuld. **NA** de switch uitgevoerd (DRY fix)
