### ISSUE TITLE
Waarom deze class?

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/PHP_WEBSHOP#5]
https://github.com/vincentlemstra/PHP_WEBSHOP/blob/faff7201c6a1faae091516ab9fd17c9053a9c798/src/classes/api/base.api.php#L3

Functioneel gelijk aan BaseAsync ....

**Comment by vincentlemstra** [comment]
base.async.php veranderd naar base.flow.php 

Deze class voorziet nu AJAX **en** API calls
